controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
      ros__parameters:
        use_sim_time: true
        left_wheel_names: ["left_front_rev", "left_back_rev"]
        right_wheel_names: ["right_front_rev", "right_back_rev"]
        wheel_separation: 0.64
        wheel_radius: 0.2
        cmd_vel_timeout: 0.5
        publish_rate: 50.0
        base_frame_id: base_link
        odom_frame_id: odom
        enable_odom_tf: true
        position_feedback: false
        linear:
          x:
            has_velocity_limits: true
            max_velocity: 2.0
            min_velocity: -2.0
            has_acceleration_limits: true
            max_acceleration: 2.5
        angular:
          z:
            has_velocity_limits: true
            max_velocity: 3.0
            has_acceleration_limits: true
            max_acceleration: 3.2