standalone_tags:
  [
    {id: 0, size: 0.173},
    {id: 1, size: 0.173},
    {id: 2, size: 0.173},
    {id: 3, size: 0.173},
  ]
tag_bundles:
  [
    {
      name: 'localization_bundle',
      layout:
        [
          {id: 0, size: 0.17, x: 0.0000, y: 0.0000, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
          {id: 3, size: 0.17, x: -0.4172, y: 0.3859, z: 0.0346, qw: 0.9991, qx: 0.0336, qy: 0.0265, qz: -0.0001},
          {id: 1, size: 0.17, x: -0.4187, y: -0.0066, z: 0.0167, qw: 0.9991, qx: -0.0087, qy: 0.0412, qz: 0.0075},
          {id: 2, size: 0.17, x: 0.0046, y: 0.3932, z: 0.0183, qw: 0.9990, qx: 0.0437, qy: -0.0018, qz: -0.0042}
        ]
    }
  ]

