costmap:
  costmap:
    ros__parameters:
      publish_frequency: 30.0
      global_frame: "odom"
      robot_base_frame: "base_link"
      robot_radius: 0.625
      plugins: ["static_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_topic: "/rtabmap/octomap_grid"
        enabled: true
        map_subscribe_transient_local: false
        subscribe_to_updates: true
        transform_tolerance: 0.1
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 1.5
        cost_scaling_factor: 6.0
        inflate_unknown: true  # should treat unknown as obstacles (maybe change init values)
        inflate_around_unknown: true
